wants:
  # Target want that dynamically generates other wants from qnet-pipeline recipe
  - metadata:
      name: qnet-target
      type: target
      labels:
        role: orchestrator
        category: dynamic-generator
    spec:
      # Target-specific parameters
      params:
        max_display: 10000
      # Recipe to use for dynamic want generation
      recipe: "recipes/qnet-pipeline.yaml"
      # Parameters to pass to the recipe
      recipe_params:
        prefix: "qnet-dynamic"
        primary_count: 5000
        secondary_count: 4000
        primary_rate: 2.0
        secondary_rate: 3.0
        primary_service_time: 0.05
        secondary_service_time: 0.05
        final_service_time: 0.03