# QNet configuration using recipe system with parameterized using fields
recipe:
  path: "recipes/qnet-pipeline.yaml"
  parameters:
    prefix: "qnet-recipe"
    primary_count: 8000
    secondary_count: 6000
    primary_rate: 2.5
    secondary_rate: 3.5
    primary_service_time: 0.08
    secondary_service_time: 0.10
    final_service_time: 0.04