nodes:
  - metadata:
      name: number-target-dry
      type: target
      labels:
        owner: parent
        category: display
    spec:
      template: "wait time in queue system"
      params:
        max_display: 200
        count: 1000
        rate: 50
        service_time: 0.01
        deterministic: false
        custom_param: "test_value"