nodes:
  - metadata:
      name: number-target
      type: target
      labels:
        owner: parent
        category: display
    spec:
      template: "number-processing-pipeline"
      params:
        max_display: 200
        count: 150
        rate: 25.0
        service_time: 0.05
        custom_param: "test_value"
