nodes:
  # Number generator - produces consecutive integers for prime testing
  - metadata:
      name: number-generator
      type: prime_generator
      labels:
        role: source
        stage: input
    spec:
      params:
        start: 2
        end: 100

  # Prime filter for 2 (removes even numbers)
  - metadata:
      name: filter-2
      type: prime_filter
      labels:
        role: filter
        prime: "2"
        stage: sieve
    spec:
      params:
        prime: 2
      inputs:
        - role: source

  # Prime filter for 3 (removes multiples of 3)
  - metadata:
      name: filter-3
      type: prime_filter
      labels:
        role: filter
        prime: "3"
        stage: sieve
    spec:
      params:
        prime: 3
      inputs:
        - prime: "2"

  # Prime filter for 5 (removes multiples of 5)
  - metadata:
      name: filter-5
      type: prime_filter
      labels:
        role: filter
        prime: "5"
        stage: sieve
    spec:
      params:
        prime: 5
      inputs:
        - prime: "3"

  # Prime filter for 7 (removes multiples of 7)
  - metadata:
      name: filter-7
      type: prime_filter
      labels:
        role: filter
        prime: "7"
        stage: sieve
    spec:
      params:
        prime: 7
      inputs:
        - prime: "5"

  # Prime detector - identifies numbers that survived all filters
  - metadata:
      name: prime-detector
      type: prime_detector
      labels:
        role: detector
        stage: detection
    spec:
      inputs:
        - prime: "7"

  # Prime collector - gathers and displays results
  - metadata:
      name: prime-collector
      type: prime_collector
      labels:
        role: sink
        stage: output
    spec:
      inputs:
        - role: detector