nodes:
  - metadata:
      name: gen
      type: sequence
      labels:
        role: source
    spec:
      params:
        rate: 2.0
        count: 100

  - metadata:
      name: q1
      type: queue
      labels:
        stage: first
    spec:
      params:
        service_time: 0.5
      inputs:
        - role: source

  - metadata:
      name: q2
      type: queue
      labels:
        stage: second
    spec:
      params:
        service_time: 0.8
      inputs:
        - stage: first

  - metadata:
      name: end
      type: sink
      labels:
        role: sink
    spec:
      inputs:
        - stage: second