nodes:
  # Two generators
  - metadata:
      name: gen1
      type: generator
      labels:
        role: source1
    spec:
      params:
        rate: 1.0
        count: 5

  - metadata:
      name: gen2
      type: generator
      labels:
        role: source2
    spec:
      params:
        rate: 2.0
        count: 5

  # Two queues processing different streams
  - metadata:
      name: q1
      type: queue
      labels:
        path: path1
    spec:
      params:
        service_time: 0.5
      inputs:
        - role: source1

  - metadata:
      name: q2
      type: queue
      labels:
        path: path2
    spec:
      params:
        service_time: 0.8
      inputs:
        - role: source2

  # Combiner merges both streams
  - metadata:
      name: merge
      type: combiner
      labels:
        role: merger
    spec:
      inputs:
        - path: path1
        - path: path2

  # Final processing
  - metadata:
      name: final
      type: queue
      labels:
        stage: final
    spec:
      params:
        service_time: 0.3
      inputs:
        - role: merger

  # End point
  - metadata:
      name: end
      type: sink
      labels:
        role: sink
    spec:
      inputs:
        - stage: final