wants:
  - metadata:
      name: number-target
      type: target
      labels:
        owner: parent
        category: display
    spec:
      template: "wait time in queue system"
      params:
        rate: 50
        service_time: 0.01
