wants:
  - metadata:
      name: queue-calculation-target
      type: "wait time in queue system"
      labels:
        owner: parent
        category: display
    spec:
      params:
        max_display: 100
        count: 1000
        rate: 10.0
        service_time: 0.1
        deterministic: false