# Prime Sieve Recipe Configuration
# Uses the prime-sieve recipe to generate and filter prime numbers

recipe:
  path: "recipes/prime-sieve.yaml"
  parameters:
    prefix: "prime-sieve"
    display_name: "Prime Number Sieve (1-100)"
    start_number: 1
    end_number: 20
    description: "Generate and filter prime numbers from 1 to 100"