wants:
  - metadata:
      name: fibonacci-sequence-want
      type: "fibonacci sequence"
      labels:
        category: fibonacci
    spec:
      recipe: recipes/fibonacci-sequence.yaml
      params:
        count: 15
        min_value: 1
        max_value: 100