wants:
  # Seed generator provides initial fibonacci values (0, 1)
  - metadata:
      name: seed-generator
      type: seed_numbers
      labels:
        role: source
        stage: initial
        component: seed
    spec:
      params:
        max_count: 20

  # Fibonacci computer calculates next fibonacci numbers
  - metadata:
      name: fibonacci-computer
      type: fibonacci_computer
      labels:
        role: processor
        stage: computation
        component: calculator
    spec:
      params: {}
      using:
        - role: merger

  # Merger combines seed values with computed values creating feedback loop
  - metadata:
      name: fibonacci-merger
      type: fibonacci_merger
      labels:
        role: merger
        stage: combine
        stream: fibonacci
    spec:
      params: {}
      using:
        - role: source
        - role: processor

