wants:
  - metadata:
      name: luxury-hotel-booking
      type: hotel
      labels:
        category: accommodation
        priority: high
    spec:
      params:
        hotel_type: luxury
        check_in: "2025-09-20"
        check_out: "2025-09-22"
        location: "Tokyo"
      requires:
        - hotel_reservation