wants:
  # Prime number generator
  - metadata:
      name: generator
      type: prime_numbers
      labels:
        role: source
    spec:
      params:
        start: 1
        end: 100

  # Prime sequence that filters out non-prime numbers
  - metadata:
      name: prime_sequence
      type: prime_sequence
      labels:
        role: filter
    spec:
      params: {}
      using:
        - role: source

  # Sink that collects and displays prime numbers
  - metadata:
      name: sink
      type: sink
      labels:
        role: collector
    spec:
      params: {}
      using:
        - role: filter