wants:
  # Target want that dynamically generates travel wants from travel-itinerary recipe
  - metadata:
      name: travel-planner-target
      type: "travel itinerary planner"
      labels:
        role: orchestrator
        category: travel-coordinator
    spec:
      # Target-specific parameters
      params:
        max_display: 10
        prefix: "vacation"
        display_name: "Weekend Vacation Itinerary" 
        restaurant_type: "michelin starred"
        hotel_type: "boutique"
        buffet_type: "continental"
        dinner_duration: 2.5